### ISSUE TITLE
Could we mention "Low Speed (LS)" somewhere?

### ISSUE THREAD

**Issue by daniel-thompson** [96boards/pinout#16]
When talking about pins on the forums (and elsewhere) one normally prefixes them with the connector (LS-UART1, LS-GPIO-A, etc). This is especially important with UARTs because several boards attach "UART4" to "LS-UART1" so without the prefix nobody can be sure which UART one is actually talking about.

I'm planning to link to the pinout in parts of the docs too. It would therefore be useful if "Low Speed (LS) Connector" appeared somewhere on the pinout page.

**Comment by fixxxxxxer** [comment]
@ric96 + 1 from me, @daniel-thompson
