### ISSUE TITLE
High-speed connector pinout is missing

### ISSUE THREAD

**Issue by fandrei** [96boards/pinout#18]
The board specs mention 40-pin low speed and 60-pin high speed connectors, but https://www.96boards.org/pinout/ only contains the pinout for the 40-pin connector.
Also, it would be very useful to specify what physical connector types are used.

**Comment by Thore-Krug** [comment]
> Also, it would be very useful to specify what physical connector types are used.

What exactly do you mean by that?  If you mean the Connectors used for mezzanines there are the following connectors specified:

**Low Speed**

- MOLEX 87831-4029 (Through hole shrouded)
- FCI ​57202-G52-20LF (SMT no shroud)
- SAMTEC TMMH-120-01-F (Through hole)

**High-Speed**

- FCI  61083-063400LF
- TE 5179030-2

 You can find more info here: https://github.com/96boards/documentation/blob/master/mezzanine/files/mezzanine-design-guidelines.pdf

**Comment by fandrei** [comment]
@Thore-Krug thanks, that's what I needed.
I don't see the pinout for the 60-pin connector, though.

**Comment by Thore-Krug** [comment]
@fandrei This info can be found in the CE Specification Docs.  ( Page 20 ) 

https://www.96boards.org/documentation/Specifications/96Boards-CE-Specification.pdf

**Comment by fandrei** [comment]
@Thore-Krug thanks
