### ISSUE TITLE
Pinout File names

### ISSUE THREAD

**Issue by shovanco** [96boards/pinout#2]
On the output folder, we need to amend the following

https://github.com/ric96/Pinout.xyz/tree/master/output/en
1. index.html = pinout.html 
- or move this inside /pinout/ folder
2. boards.html = pinout-boards.html
3. /resources/ = /pinout-resources/
- or move this into /pinout/resources/
4. inside the /pinout/ folder have index.html which should redirect to pinout.html 
https://github.com/ric96/Pinout.xyz/tree/master/output/en/pinout or move pinout.html to this folder
5. All the links on the page should have .html extension

**Comment by ric96** [comment]
@shovanuk what about renaming the pinouts folder as data and move resources under data?

**Comment by ric96** [comment]
I've found a link that still redirects to the 96boards website, rather than the pinouts website... I'll take a look first thing today morning.

**Comment by fixxxxxxer** [comment]
@ric96 what is the status on this issue, it is over a month old.

Please address the status or close.

Thanks.

**Comment by ric96** [comment]
solved
